// Stable built-in furniture metadata. Keep this module data-only so catalog, editor and model can
// depend on it without pulling geometry, rendering or Home Assistant behavior into their graph.

export const FURNITURE_TYPES = [
  "lamp_ceiling",
  "lamp_downlight",
  "lamp_spot",
  "lamp_panel",
  "lamp_pendant",
  "lamp_floor",
  "lamp_table",
  "lamp_wall",
  "led_strip",
  "lamp_uplight",
  "lamp_bollard",
  "lamp_garden",
  "lamp_column",
  "lamp_tv_bars",
  "lamp_orb_table",
  "lamp_portable",
  "lamp_ambient_spot",
  "lamp_cube",
  "lamp_panel_round",
  "lamp_garden_spots",
  "lamp_wall_updown",
  "radiator",
  "air_conditioner",
  "water_pump",
  "altar",
  "altar_wall",
  "shoe_cabinet",
  "motorbike",
  "fan_ceiling",
  "fan_ceiling_light",
  "fan_wall",
  "fan_floor",
  "water_heater",
  "drying_rack",
  "shoe_bench",
  "room_divider",
  "range_hood",
  "microwave",
  "water_purifier",
  "air_purifier",
  "smart_speaker",
  "security_camera",
  "smart_lock",
  "smart_curtain",
  "network_cabinet",
  "nas_server",
  "access_point",
  "wall_thermostat",
  "smoke_detector",
  "siren_alarm",
  "electrical_panel",
  "ups_unit",
  "modem_router",
  "heat_pump_outdoor",
  "hot_water_tank",
  "ventilation_fan",
  "humidifier",
  "smart_display",
  "wall_switch",
  "wall_outlet",
  "smart_plug",
  "motion_sensor",
  "contact_sensor",
  "water_leak_sensor",
  "temperature_humidity_sensor",
  "video_doorbell",
  "kitchen_corner",
  "kitchen_display",
  "vanity",
  "crib",
  "bed_single",
  "bed_double",
  "sofa_l",
  "sofa_bed",
  "shower_screen",
  "hammock",
  "stone_table_set",
  "planter_large",
  "water_tank",
  "gate",
  "fence",
  "sofa",
  "armchair",
  "stool",
  "coffee_table",
  "tv_board",
  "tv_wall",
  "sideboard",
  "shelf",
  "plant",
  "rug",
  "table",
  "table_round",
  "chair",
  "bench",
  "corner_bench",
  "bar_stool",
  "kitchen",
  "kitchen_wall",
  "kitchen_tall",
  "island",
  "worktop",
  "sink",
  "stove",
  "dishwasher",
  "fridge",
  "bed",
  "bunk_bed",
  "nightstand",
  "wardrobe",
  "dresser",
  "bathtub",
  "shower",
  "wc",
  "washbasin",
  "washer",
  "dryer",
  "washer_dryer_tower",
  "balcony_solar",
  "desk",
  "office_chair",
  "tall_cabinet",
  "coat_rack",
  "stairs",
  "stairs_landing",
  "robot_vacuum",
  "robot_mower",
  "inverter",
  "home_battery",
  "wallbox",
  "meter",
  "grid_point",
  "parking",
  "fridge_smart",
  "stairwell",
] as const;

export type FurnitureType = (typeof FURNITURE_TYPES)[number];

/** Furniture library sections (the editor lists them in this order). */
export const FURNITURE_GROUPS: Record<string, FurnitureType[]> = {
  lights: ["lamp_ceiling", "lamp_downlight", "lamp_spot", "lamp_panel", "lamp_panel_round", "lamp_pendant", "lamp_floor", "lamp_uplight", "lamp_column", "lamp_tv_bars", "lamp_table", "lamp_orb_table", "lamp_portable", "lamp_ambient_spot", "lamp_cube", "lamp_wall", "lamp_wall_updown", "led_strip", "lamp_bollard", "lamp_garden", "lamp_garden_spots"],
  living: ["sofa", "sofa_l", "sofa_bed", "armchair", "stool", "coffee_table", "tv_board", "tv_wall", "smart_display", "smart_speaker", "smart_curtain", "sideboard", "shelf", "room_divider", "altar", "altar_wall", "plant", "rug"],
  dining: ["table", "table_round", "chair", "bench", "corner_bench", "bar_stool"],
  kitchen: ["kitchen", "kitchen_corner", "kitchen_wall", "kitchen_tall", "kitchen_display", "island", "worktop", "sink", "stove", "range_hood", "microwave", "water_purifier", "dishwasher", "fridge"],
  sleeping: ["bed", "bed_single", "bed_double", "bunk_bed", "crib", "nightstand", "wardrobe", "dresser", "vanity"],
  bath: ["bathtub", "shower", "shower_screen", "wc", "washbasin", "water_heater", "hot_water_tank", "washer", "dryer", "washer_dryer_tower", "drying_rack"],
  climate: ["air_conditioner", "heat_pump_outdoor", "air_purifier", "humidifier", "radiator", "wall_thermostat", "temperature_humidity_sensor", "ventilation_fan", "fan_ceiling", "fan_ceiling_light", "fan_wall", "fan_floor"],
  outdoor: ["security_camera", "video_doorbell", "smart_lock", "water_pump", "robot_mower", "balcony_solar", "hammock", "stone_table_set", "planter_large", "water_tank", "gate", "fence"],
  work: ["desk", "worktop", "office_chair", "tall_cabinet", "coat_rack", "shoe_cabinet", "shoe_bench", "wall_switch", "wall_outlet", "smart_plug", "motion_sensor", "contact_sensor", "water_leak_sensor", "network_cabinet", "nas_server", "modem_router", "electrical_panel", "ups_unit", "access_point", "smoke_detector", "siren_alarm", "stairs", "stairs_landing", "robot_vacuum"],
  vehicles: ["motorbike", "parking"],
};

/** Energy devices: placed and set up in the Energy tool (stored like furniture, not in the library). */
export const ENERGY_DEVICES = ["meter", "inverter", "home_battery", "wallbox", "grid_point"] as const;

/** Lamps: drawn live (they glow with their light) and tapped directly in 3D. */
export const LAMP_TYPES = new Set<string>([
  "lamp_ceiling",
  "lamp_downlight",
  "lamp_spot",
  "lamp_panel",
  "lamp_pendant",
  "lamp_floor",
  "lamp_uplight",
  "lamp_table",
  "lamp_wall",
  "led_strip",
  "lamp_bollard",
  "lamp_garden",
  "lamp_column",
  "lamp_tv_bars",
  "lamp_orb_table",
  "lamp_portable",
  "lamp_ambient_spot",
  "lamp_cube",
  "lamp_panel_round",
  "lamp_garden_spots",
  "lamp_wall_updown",
]);

export const ELECTRIC_FURNITURE = new Set<string>([
  ...LAMP_TYPES,
  "radiator",
  "air_conditioner",
  "water_pump",
  "fan_ceiling",
  "fan_ceiling_light",
  "fan_wall",
  "fan_floor",
  "water_heater",
  "range_hood",
  "microwave",
  "water_purifier",
  "air_purifier",
  "smart_speaker",
  "security_camera",
  "smart_lock",
  "smart_curtain",
  "network_cabinet",
  "nas_server",
  "access_point",
  "wall_thermostat",
  "smoke_detector",
  "siren_alarm",
  "electrical_panel",
  "ups_unit",
  "modem_router",
  "heat_pump_outdoor",
  "hot_water_tank",
  "ventilation_fan",
  "humidifier",
  "smart_display",
  "wall_switch",
  "wall_outlet",
  "smart_plug",
  "motion_sensor",
  "contact_sensor",
  "water_leak_sensor",
  "temperature_humidity_sensor",
  "video_doorbell",
  "robot_vacuum",
  "robot_mower",
  "inverter",
  "home_battery",
  "wallbox",
  "meter",
  "tv_board",
  "tv_wall",
  "desk",
  "fridge",
  "fridge_smart",
  "stove",
  "kitchen_tall",
  "kitchen_display",
  "dishwasher",
  "washer",
  "dryer",
  "washer_dryer_tower",
  "balcony_solar",
  "kitchen",
  "island",
  "sink",
]);

/** Default size (width x, depth z, height) of new furniture in metres. */
export const FURNITURE_SIZE: Record<FurnitureType, [number, number, number]> = {
  sofa: [2.2, 0.9, 0.82],
  armchair: [0.85, 0.85, 0.8],
  table: [1.6, 0.9, 0.75],
  chair: [0.46, 0.5, 0.9],
  bed: [1.6, 2.05, 0.9],
  nightstand: [0.45, 0.4, 0.5],
  wardrobe: [1.8, 0.6, 2.1],
  shelf: [0.9, 0.35, 1.9],
  kitchen: [2.4, 0.62, 0.92],
  // a worktop on its own (over a gap, on self-built desk pedestals): the height is its top edge
  worktop: [1.2, 0.62, 0.91],
  // solar inverter and wallbox hang on the wall, the home battery stands on the floor
  inverter: [0.5, 0.2, 0.65],
  home_battery: [0.6, 0.25, 1.1],
  wallbox: [0.3, 0.15, 0.42],
  // the meter cabinet hangs on the wall as well
  meter: [0.55, 0.21, 1.1],
  // the grid connection: a small street cabinet at the edge of the plot
  grid_point: [0.4, 0.22, 0.6],
  fridge: [0.6, 0.65, 1.8],
  fridge_smart: [0.91, 0.73, 1.78],
  stairwell: [1.0, 2.6, 0.02],
  stove: [0.6, 0.62, 0.92],
  sink: [0.9, 0.62, 0.92],
  bathtub: [1.7, 0.75, 0.58],
  shower: [0.9, 0.9, 2.0],
  wc: [0.38, 0.6, 0.8],
  washbasin: [0.6, 0.46, 0.85],
  desk: [1.4, 0.7, 0.75],
  tv_board: [1.8, 0.42, 0.5],
  plant: [0.45, 0.45, 1.1],
  rug: [2.0, 1.4, 0.01],
  stairs: [1.0, 3.2, 2.75],
  stairs_landing: [2.1, 3.2, 2.75],
  stool: [0.55, 0.55, 0.42],
  lamp_ceiling: [0.4, 0.4, 0.08],
  lamp_downlight: [0.1, 0.1, 0.02],
  lamp_spot: [0.1, 0.1, 0.14],
  lamp_panel: [0.6, 0.6, 0.03],
  lamp_uplight: [0.35, 0.35, 1.8],
  lamp_bollard: [0.16, 0.16, 0.8],
  lamp_garden: [0.12, 0.12, 0.3],
  lamp_column: [0.12, 0.12, 1.45],
  lamp_tv_bars: [0.65, 0.16, 0.38],
  lamp_orb_table: [0.28, 0.28, 0.24],
  lamp_portable: [0.24, 0.24, 0.26],
  lamp_ambient_spot: [0.2, 0.2, 0.2],
  lamp_cube: [0.26, 0.26, 0.24],
  lamp_panel_round: [0.42, 0.42, 0.045],
  lamp_garden_spots: [0.65, 0.18, 0.32],
  lamp_wall_updown: [0.14, 0.12, 0.32],
  radiator: [1.0, 0.1, 0.6],
  air_conditioner: [1.0, 0.22, 0.3],
  water_pump: [0.55, 0.4, 0.45],
  altar: [1.27, 0.61, 1.53],
  altar_wall: [0.89, 0.48, 0.48],
  shoe_cabinet: [1.0, 0.35, 1.0],
  motorbike: [0.72, 1.9, 1.15],
  fan_ceiling: [1.4, 1.4, 0.32],
  fan_ceiling_light: [1.4, 1.4, 0.4],
  fan_wall: [0.5, 0.3, 0.5],
  fan_floor: [0.45, 0.45, 1.25],
  water_heater: [0.75, 0.35, 0.45],
  drying_rack: [1.6, 0.6, 1.7],
  shoe_bench: [1.0, 0.38, 0.48],
  room_divider: [1.6, 0.3, 2.1],
  range_hood: [0.75, 0.5, 0.5],
  microwave: [0.5, 0.4, 0.3],
  water_purifier: [0.42, 0.38, 1.2],
  air_purifier: [0.32, 0.32, 0.65],
  smart_speaker: [0.14, 0.14, 0.19],
  security_camera: [0.2, 0.24, 0.22],
  smart_lock: [0.1, 0.08, 0.32],
  smart_curtain: [2.0, 0.16, 2.2],
  network_cabinet: [0.6, 0.65, 1.35],
  nas_server: [0.42, 0.45, 0.34],
  access_point: [0.24, 0.24, 0.055],
  wall_thermostat: [0.18, 0.065, 0.24],
  smoke_detector: [0.15, 0.15, 0.055],
  siren_alarm: [0.22, 0.085, 0.28],
  electrical_panel: [0.55, 0.14, 0.8],
  ups_unit: [0.45, 0.5, 0.72],
  modem_router: [0.34, 0.22, 0.12],
  heat_pump_outdoor: [1.0, 0.48, 0.86],
  hot_water_tank: [0.55, 0.55, 1.3],
  ventilation_fan: [0.32, 0.14, 0.32],
  humidifier: [0.38, 0.38, 0.8],
  smart_display: [0.55, 0.16, 0.36],
  wall_switch: [0.09, 0.045, 0.09],
  wall_outlet: [0.09, 0.045, 0.09],
  smart_plug: [0.1, 0.08, 0.12],
  motion_sensor: [0.11, 0.08, 0.11],
  contact_sensor: [0.11, 0.04, 0.05],
  water_leak_sensor: [0.09, 0.09, 0.035],
  temperature_humidity_sensor: [0.1, 0.045, 0.1],
  video_doorbell: [0.055, 0.045, 0.14],
  kitchen_corner: [1.25, 1.25, 0.92],
  kitchen_display: [0.8, 0.42, 2.1],
  vanity: [1.0, 0.45, 1.55],
  crib: [0.75, 1.25, 0.95],
  bed_single: [1.0, 2.05, 0.9],
  bed_double: [1.8, 2.05, 0.9],
  sofa_l: [2.5, 1.7, 0.82],
  sofa_bed: [2.0, 1.35, 0.78],
  shower_screen: [1.0, 0.08, 1.9],
  hammock: [2.6, 0.9, 1.2],
  stone_table_set: [2.2, 2.2, 0.75],
  planter_large: [0.8, 0.8, 1.6],
  water_tank: [1.25, 1.25, 1.55],
  gate: [3.2, 0.18, 1.8],
  fence: [2.4, 0.16, 1.5],
  robot_vacuum: [0.42, 0.62, 0.72],
  robot_mower: [0.85, 1.15, 0.48],
  parking: [2.6, 5.2, 0.02],
  lamp_pendant: [0.4, 0.4, 0.8],
  lamp_floor: [0.4, 0.4, 1.7],
  lamp_table: [0.28, 0.28, 0.45],
  lamp_wall: [0.22, 0.12, 0.2],
  led_strip: [2.0, 0.04, 0.03],
  coffee_table: [1.1, 0.6, 0.42],
  tv_wall: [1.3, 0.08, 0.75],
  sideboard: [1.6, 0.45, 0.8],
  table_round: [1.1, 1.1, 0.75],
  bench: [1.4, 0.45, 0.85],
  corner_bench: [2.0, 1.6, 0.9],
  bar_stool: [0.42, 0.42, 0.75],
  kitchen_wall: [0.8, 0.35, 0.7],
  kitchen_tall: [0.6, 0.62, 2.1],
  island: [1.8, 0.9, 0.92],
  dishwasher: [0.6, 0.62, 0.92],
  bunk_bed: [1.0, 2.05, 1.65],
  dresser: [1.0, 0.5, 0.9],
  washer: [0.6, 0.6, 0.85],
  dryer: [0.6, 0.6, 0.85],
  washer_dryer_tower: [0.66, 0.68, 1.75],
  balcony_solar: [1.65, 0.72, 1.05],
  office_chair: [0.65, 0.65, 1.1],
  tall_cabinet: [0.6, 0.6, 2.1],
  coat_rack: [1.0, 0.35, 1.9],
};
